### ISSUE TITLE
Feature Request and Questions

### ISSUE THREAD

**Issue by Julienraptor01** [EyezahMC/Cosmetica#16]
Hello, i just found the mod and have some questions and features request.

First where is stored the config ? Because i can't find id in my .minecraft folder in the config or elsewhere.
The feature request associated would be that in modmenu the settings could be accessible and that by editing the config file manually we could disable the vanilla integration. I would like that because personnally i prefer having all mods configs in one place.

Second thing is in what order are the cape prefered and could we customize the order in the future ? Could you add other capes in the future and support custom capes API because i would like to add my cutom cape API for only me and my friends. and the other cape API that you don't support that i think of is Wynntils.

**Comment by eyezahhhh** [comment]
Welcome to Cosmetica! The config is stored on the server because those settings determine what information the server sends to your client. We're adding a local config file in the next update which will control all local settings (but not toggling cosmetics, etc).

We do have modmenu integration planned so yeah we can discuss allowing for exclusive modmenu integration by modifying the config file.

The cape hierarchy is Cosmetica > Cloaks+ > Arc > Mantle > LabyMod > MinecraftCapes.net > Optifine > Minecraft. This will be configurable in future. I'll look into supporting Wynntils.

By your own Cape API, do you intend for these capes to be visible to you and your friends across all servers or just a specific minecraft server(s) that you run?

**Comment by Julienraptor01** [comment]
Thanks for all theses infos. For my custom capes for me and my friend i would like it to be visible on every server but only for me and my friend. I would give my API for the cape to them so they could add it in some config like i would give them www.julienraptor01.uwu/capes/<uuid>.png and they could put that into a section like private API that would go on top of all the other API

**Comment by eyezahhhh** [comment]
We see Cosmetica as a global cosmetics mod in which everybody can see everyone else's Cosmetica cosmetics, unfortunately this wouldn't align with that philosophy with you and your friend in your own cosmetics "bubble". The idea for Cosmetica is anyone can use a cosmetic they see on anyone else but following this idea most people wouldn't be able to see your cape. If you and your friend want to see each other's capes you can upload and equip them via Cosmetica.
