### ISSUE TITLE
Animated capes

### ISSUE THREAD

**Issue by Madis0** [EyezahMC/Cosmetica#40]
It has been said that this is not yet supported, so it should be, at least on non-Cosmetica cape servers.

**Comment by valoeghese** [comment]
Hello there!

Thanks for contributing to feature suggestions for Cosmetica.

All three of your suggestions have been planned for a while, however due to time constraints, some will come much later than 
others (In particular #39. We want to get a modern forge port working before we do backports. In addition, we will backport to versions in order based on demand.)

Out of the three, I actually wanted to add Animated Cape support to Cosmetica soon, so you can probably expect this in the next few updates.

If you have more feature suggestions, please be sure to join the discord. We have a whole channel for feature suggestions where members can upvote and downvote each suggestion!

https://discord.gg/aQh5SJEUBm

**Comment by eyezahhhh** [comment]
Released in [1.2.0](https://cosmetica.cc/join).
